//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.FACTURA_PRODUCTO = new HashSet<FACTURA_PRODUCTO>();
        }
    
        public int N_DOC_USUARIO { get; set; }
        public int COD_FACTURA { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO { get; set; }
        public decimal VALOR_PAGADO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_PRODUCTO> FACTURA_PRODUCTO { get; set; }
    }
}
