//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeEntidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VENTASEntities1 : DbContext
    {
        public VENTASEntities1()
            : base("name=VENTASEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FACTURA> FACTURA { get; set; }
        public virtual DbSet<FACTURA_PRODUCTO> FACTURA_PRODUCTO { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int SP_ActualizarUsuario(string nOMBRE, string aPELLIDO, string tIPO_DOC, Nullable<int> nUM_DOCUMENTO, Nullable<System.DateTime> fECHA_NACIMIENTO, string gENERO, string eMAIL)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var tIPO_DOCParameter = tIPO_DOC != null ?
                new ObjectParameter("TIPO_DOC", tIPO_DOC) :
                new ObjectParameter("TIPO_DOC", typeof(string));
    
            var nUM_DOCUMENTOParameter = nUM_DOCUMENTO.HasValue ?
                new ObjectParameter("NUM_DOCUMENTO", nUM_DOCUMENTO) :
                new ObjectParameter("NUM_DOCUMENTO", typeof(int));
    
            var fECHA_NACIMIENTOParameter = fECHA_NACIMIENTO.HasValue ?
                new ObjectParameter("FECHA_NACIMIENTO", fECHA_NACIMIENTO) :
                new ObjectParameter("FECHA_NACIMIENTO", typeof(System.DateTime));
    
            var gENEROParameter = gENERO != null ?
                new ObjectParameter("GENERO", gENERO) :
                new ObjectParameter("GENERO", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarUsuario", nOMBREParameter, aPELLIDOParameter, tIPO_DOCParameter, nUM_DOCUMENTOParameter, fECHA_NACIMIENTOParameter, gENEROParameter, eMAILParameter);
        }
    
        public virtual int SP_EliminarUsuario(Nullable<int> nUM_DOCUMENTO)
        {
            var nUM_DOCUMENTOParameter = nUM_DOCUMENTO.HasValue ?
                new ObjectParameter("NUM_DOCUMENTO", nUM_DOCUMENTO) :
                new ObjectParameter("NUM_DOCUMENTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarUsuario", nUM_DOCUMENTOParameter);
        }
    
        public virtual int SP_InsertarUsuario(string nOMBRE, string aPELLIDO, string tIPO_DOC, Nullable<int> nUM_DOCUMENTO, Nullable<System.DateTime> fECHA_NACIMIENTO, string gENERO, string eMAIL)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var tIPO_DOCParameter = tIPO_DOC != null ?
                new ObjectParameter("TIPO_DOC", tIPO_DOC) :
                new ObjectParameter("TIPO_DOC", typeof(string));
    
            var nUM_DOCUMENTOParameter = nUM_DOCUMENTO.HasValue ?
                new ObjectParameter("NUM_DOCUMENTO", nUM_DOCUMENTO) :
                new ObjectParameter("NUM_DOCUMENTO", typeof(int));
    
            var fECHA_NACIMIENTOParameter = fECHA_NACIMIENTO.HasValue ?
                new ObjectParameter("FECHA_NACIMIENTO", fECHA_NACIMIENTO) :
                new ObjectParameter("FECHA_NACIMIENTO", typeof(System.DateTime));
    
            var gENEROParameter = gENERO != null ?
                new ObjectParameter("GENERO", gENERO) :
                new ObjectParameter("GENERO", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertarUsuario", nOMBREParameter, aPELLIDOParameter, tIPO_DOCParameter, nUM_DOCUMENTOParameter, fECHA_NACIMIENTOParameter, gENEROParameter, eMAILParameter);
        }
    
        public virtual ObjectResult<SP_ListarUsuarios_Result> SP_ListarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListarUsuarios_Result>("SP_ListarUsuarios");
        }
    }
}
